In [1]:
import pandas as pd
import numpy as np

import os
wd = os.getcwd()
wd

'C:\\Users\\Nils\\Documents\\KIT-TVWL\\Master\\SS 18\\KD Seminar\\Git\\mlp'

In [2]:
df = pd.read_csv("../final_data/complete_data.csv")
df.Timestamp = pd.to_datetime(df.Timestamp)
df = df.drop(["Unnamed: 0"], axis=1)
df.head()

Timestamp       ID  articleCount  avgSentiment  stdSentiment  \
0 2017-06-01  Samsung            50      0.165618      0.171879   
1 2017-06-01    Apple            50      0.160381      0.204606   
2 2017-06-01   Airbus            50      0.175252      0.163460   
3 2017-06-01    Bayer            50      0.279171      0.181638   
4 2017-06-01      BMW            50      0.079084      0.205928   

   25quantileSentiment  50quantileSentiment  75quantileSentiment  \
0             0.084830             0.182180             0.267473   
1             0.045303             0.205475             0.304395   
2             0.076917             0.163210             0.301123   
3             0.093412             0.279715             0.386053   
4             0.038152             0.111880             0.210670   

   maxSentiment  minSentiment  socialScore  nbOfDuplicates  \
0     -0.392611       0.46335         1922               2   
1     -0.486920       0.48226        14547               4   
2     -0.128650       0.46700         1218               5   
3     -0.031140       0.71335         8477               7   
4     -0.537689       0.35647         3539               1   

   Previous_Day_Return  Next_Day_Return  
0            -0.000448         0.028245  
1             0.002746         0.014710  
2             0.029297         0.004381  
3             0.008012         0.021193  
4             0.019381         0.011823

In [3]:
df.columns

Index(['Timestamp', 'ID', 'articleCount', 'avgSentiment', 'stdSentiment',
       '25quantileSentiment', '50quantileSentiment', '75quantileSentiment',
       'maxSentiment', 'minSentiment', 'socialScore', 'nbOfDuplicates',
       'Previous_Day_Return', 'Next_Day_Return'],
      dtype='object')

**For now, drop every Column related to IBM**

In [10]:
df = df.dropna(axis=1, how="all")
df.head()

25quantileSentiment  50quantileSentiment  75quantileSentiment       ID  \
0            -0.055740             0.000000             0.103619    Bayer   
1            -0.230230            -0.094850             0.091920  Allianz   
2            -0.070315             0.072627             0.202486    Tesla   
3            -0.056716             0.029800             0.205750    Apple   
4            -0.189105             0.000000             0.134490      BMW   

   Timestamp  analytical_count  anger_count  articleCount  avgSentiment  \
0 2018-05-02               NaN          NaN          3035      0.024029   
1 2018-05-02               NaN          NaN           121     -0.052265   
2 2018-05-02               NaN          NaN           510      0.068932   
3 2018-05-02               NaN          NaN          3116      0.050277   
4 2018-05-02               NaN          NaN           500     -0.013354   

   confident_count  fear_count  ibm_articleCount  joy_count  maxSentiment  \
0              NaN         NaN               NaN        NaN       0.68469   
1              NaN         NaN               NaN        NaN       0.58215   
2              NaN         NaN               NaN        NaN       0.64572   
3              NaN         NaN               NaN        NaN       0.92600   
4              NaN         NaN               NaN        NaN       0.93410   

   minSentiment  sadness_count  stdSentiment  tentative_count  \
0     -0.512460            NaN      0.166494              NaN   
1     -0.662970            NaN      0.264638              NaN   
2     -0.503000            NaN      0.173565              NaN   
3     -0.886267            NaN      0.217317              NaN   
4     -0.676800            NaN      0.233298              NaN   

   Previous_Day_Return  Next_Day_Return  
0             0.003419         0.003507  
1             0.013549        -0.009181  
2             0.004093        -0.057051  
3             0.043227         0.001811  
4             0.006682        -0.010041

In case financial Data is not complete, Drop days without financial data

In [12]:
df = df.dropna(axis=0, how="any")
df

25quantileSentiment  50quantileSentiment  75quantileSentiment  \
120             0.045730             0.161330             0.284240   
121            -0.136990             0.037860             0.156510   
122             0.005672             0.168750             0.310433   
123             0.128430             0.250895             0.347670   
124             0.075980             0.169850             0.272675   
125             0.118570             0.200840             0.301400   
126             0.348430             0.412570             0.417530   
127             0.035100             0.178280             0.278057   
128             0.080300             0.167788             0.253690   
129            -0.317590            -0.069190             0.112530   
130             0.063640             0.153905             0.271969   

             ID  Timestamp  analytical_count  anger_count  articleCount  \
120      Google 2018-05-21               0.0          0.0          1225   
121       Tesla 2018-05-21               0.0          0.0           361   
122      Airbus 2018-05-21               0.0          0.0            66   
123       Bayer 2018-05-21               0.0          0.0           238   
124         BMW 2018-05-21               0.0          0.0           169   
125        BASF 2018-05-21               0.0          0.0           103   
126  Telefonica 2018-05-21               0.0          0.0            26   
127       Apple 2018-05-21               0.0          0.0           917   
128     Allianz 2018-05-21               0.0          0.0            33   
129       Total 2018-05-21               0.0          0.0            50   
130     Samsung 2018-05-21               0.0          0.0           432   

     avgSentiment  confident_count  fear_count  ibm_articleCount  joy_count  \
120      0.154012              0.0         0.0               0.0        0.0   
121      0.037883              0.0         0.0               0.0        0.0   
122      0.164733              0.0         0.0               0.0        0.0   
123      0.249125              0.0         0.0               0.0        0.0   
124      0.162243              0.0         0.0               0.0        0.0   
125      0.218065              0.0         0.0               0.0        0.0   
126      0.361680              0.0         0.0               0.0        0.0   
127      0.166774              0.0         0.0               0.0        0.0   
128      0.178543              0.0         0.0               0.0        0.0   
129     -0.082267              0.0         0.0               0.0        0.0   
130      0.169286              0.0         0.0               0.0        0.0   

     maxSentiment  minSentiment  sadness_count  stdSentiment  tentative_count  \
120     -0.548100      0.858800            0.0      0.203818              0.0   
121     -0.441986      0.639367            0.0      0.184853              0.0   
122     -0.341900      0.533870            0.0      0.229539              0.0   
123     -0.207700      0.713530            0.0      0.171248              0.0   
124     -0.796400      0.620920            0.0      0.212629              0.0   
125     -0.082870      0.531520            0.0      0.128144              0.0   
126      0.051060      0.460550            0.0      0.096824              0.0   
127     -0.582450      0.694250            0.0      0.184267              0.0   
128     -0.075370      0.533870            0.0      0.157595              0.0   
129     -0.669800      0.334990            0.0      0.250963              0.0   
130     -0.397360      0.706600            0.0      0.164844              0.0   

     Previous_Day_Return  Next_Day_Return  
120             0.003055        -0.011244  
121             0.027331         0.014655  
122             0.000000        -0.017312  
123             0.000000        -0.022140  
124             0.000000        -0.020353  
125             0.000000        -0.023093  
126             0.003265        -

In [4]:
df["relabeled_returns"] = df["Next_Day_Return"].apply(lambda x: -1 if x < 0 else 1)
df.head()

Timestamp       ID  articleCount  avgSentiment  stdSentiment  \
0 2017-06-01  Samsung            50      0.165618      0.171879   
1 2017-06-01    Apple            50      0.160381      0.204606   
2 2017-06-01   Airbus            50      0.175252      0.163460   
3 2017-06-01    Bayer            50      0.279171      0.181638   
4 2017-06-01      BMW            50      0.079084      0.205928   

   25quantileSentiment  50quantileSentiment  75quantileSentiment  \
0             0.084830             0.182180             0.267473   
1             0.045303             0.205475             0.304395   
2             0.076917             0.163210             0.301123   
3             0.093412             0.279715             0.386053   
4             0.038152             0.111880             0.210670   

   maxSentiment  minSentiment  socialScore  nbOfDuplicates  \
0     -0.392611       0.46335         1922               2   
1     -0.486920       0.48226        14547               4   
2     -0.128650       0.46700         1218               5   
3     -0.031140       0.71335         8477               7   
4     -0.537689       0.35647         3539               1   

   Previous_Day_Return  Next_Day_Return  relabeled_returns  
0            -0.000448         0.028245                  1  
1             0.002746         0.014710                  1  
2             0.029297         0.004381                  1  
3             0.008012         0.021193                  1  
4             0.019381         0.011823                  1

In [49]:
len(df["ID"].unique())

11

In [50]:
df.shape
no_companies = len(df["ID"].unique())
nr_days = int(df.shape[0] / no_companies)
nr_feats = df.shape[1] -4 #(-3 wegen Timestamp, ID, Next_Day_Return, relabeled_returns)
print("Days {}".format(nr_days))
print("Features {}".format(nr_feats))

Days 99
Features 11


In [6]:
df["Timestamp"].value_counts()

2017-10-30    11
2017-06-14    11
2017-10-27    11
2017-08-09    11
2017-07-06    11
2017-06-02    11
2017-07-17    11
2017-08-31    11
2017-06-13    11
2017-07-28    11
2017-09-11    11
2017-10-26    11
2017-08-08    11
2017-07-05    11
2017-06-01    11
2017-08-30    11
2017-06-12    11
2017-07-27    11
2017-10-25    11
2017-06-23    11
2017-08-07    11
2017-09-21    11
2017-08-18    11
2017-09-12    11
2017-10-16    11
2017-10-13    11
2017-09-01    11
2017-09-26    11
2017-08-23    11
2017-06-05    11
              ..
2017-08-24    11
2017-07-21    11
2017-10-19    11
2017-08-01    11
2017-06-08    11
2017-07-12    11
2017-10-24    11
2017-09-29    11
2017-06-22    11
2017-09-20    11
2017-07-03    11
2017-08-17    11
2017-07-14    11
2017-08-28    11
2017-10-12    11
2017-07-25    11
2017-09-08    11
2017-10-23    11
2017-06-21    11
2017-09-19    11
2017-08-16    11
2017-07-13    11
2017-10-11    11
2017-06-09    11
2017-07-24    11
2017-09-07    11
2017-06-20    11
2017-08-04    

In [79]:
df.tail()

Timestamp          ID  articleCount  avgSentiment  stdSentiment  \
105 2018-05-17       Tesla           297      0.065692      0.231960   
106 2018-05-17      Airbus           261     -0.002624      0.262978   
107 2018-05-17     Allianz           195     -0.048640      0.281950   
108 2018-05-17  Telefonica           115      0.088121      0.226507   
109 2018-05-17     Samsung           634      0.096998      0.206897   

     25quantileSentiment  50quantileSentiment  75quantileSentiment  \
105            -0.087833              0.05566             0.197360   
106            -0.179820              0.00000             0.162960   
107            -0.290885             -0.06882             0.127410   
108            -0.020130              0.07377             0.235167   
109             0.000000              0.07874             0.233280   

     maxSentiment  minSentiment  Previous_Day_Return  Next_Day_Return  \
105      0.747933      -0.64050            -0.006795        -0.027506   
106      0.605420      -0.54918             0.021861        -0.000714   
107      0.565740      -0.58092             0.012064        -0.001565   
108      0.622090      -0.56565            -0.026461        -0.036134   
109      0.636900      -0.89410            -0.009068         0.002022   

     relabeled_returns  
105                 -1  
106                 -1  
107                 -1  
108                 -1  
109                  1

In [30]:
X = []#np.empty((int(nr_days) ,int(nr_feats * 10)))

In [71]:
df[df["Timestamp"] == "2017-06-09"].drop(labels_to_drop, axis=1)

articleCount  avgSentiment  stdSentiment  25quantileSentiment  \
55            50      0.064389      0.170300            -0.053773   
56            50     -0.021494      0.206701            -0.163830   
57            50      0.093391      0.182092            -0.039365   
58             7      0.267743      0.120840             0.223933   
59            50      0.062489      0.147223            -0.040836   
60            27      0.143952      0.190648            -0.011715   
61            26      0.226999      0.236407             0.158572   
62            50      0.204706      0.141717             0.101705   
63            50      0.199924      0.165575             0.081953   
64            16      0.015785      0.188809            -0.101818   
65            50      0.071470      0.151924            -0.029622   

    50quantileSentiment  75quantileSentiment  maxSentiment  minSentiment  \
55             0.088515             0.148540     -0.286730      0.471467   
56            -0.017950             0.109968     -0.384340      0.443362   
57             0.078205             0.229063     -0.259830      0.550190   
58             0.228014             0.342625      0.083660      0.429410   
59             0.070840             0.145330     -0.315510      0.368650   
60             0.112060             0.186340     -0.078825      0.559510   
61             0.274125             0.325844     -0.389470      0.662362   
62             0.217100             0.313273     -0.064700      0.507530   
63             0.174050             0.312575     -0.102750      0.595100   
64             0.001170             0.089185     -0.319930      0.420450   
65             0.058355             0.190112     -0.381060      0.347900   

    socialScore  nbOfDuplicates  Previous_Day_Return  
55         2222               3            -0.017838  
56          720               4             0.022398  
57         7454               2            -0.034871  
58            7               1            -0.031230  
59         9970               1            -0.039549  
60           63               0             0.010408  
61           22               2             0.027277  
62        22662               8             0.002523  
63         6390               4             0.020601  
64           56               1             0.002020  
65         9325              15             0.003797

In [51]:
X = []
labels_to_drop = ["Timestamp", "ID", "Next_Day_Return", "relabeled_returns"]
for d in df["Timestamp"].value_counts().index:
    print(d)
    X.append(df[df["Timestamp"] == d].drop(labels_to_drop, axis=1).values.reshape(1,nr_feats*no_companies))
len(X)

2017-10-30 00:00:00
2017-06-14 00:00:00
2017-10-27 00:00:00
2017-08-09 00:00:00
2017-07-06 00:00:00
2017-06-02 00:00:00
2017-07-17 00:00:00
2017-08-31 00:00:00
2017-06-13 00:00:00
2017-07-28 00:00:00
2017-09-11 00:00:00
2017-10-26 00:00:00
2017-08-08 00:00:00
2017-07-05 00:00:00
2017-06-01 00:00:00
2017-08-30 00:00:00
2017-06-12 00:00:00
2017-07-27 00:00:00
2017-10-25 00:00:00
2017-06-23 00:00:00
2017-08-07 00:00:00
2017-09-21 00:00:00
2017-08-18 00:00:00
2017-09-12 00:00:00
2017-10-16 00:00:00
2017-10-13 00:00:00
2017-09-01 00:00:00
2017-09-26 00:00:00
2017-08-23 00:00:00
2017-06-05 00:00:00
2017-07-20 00:00:00
2017-10-18 00:00:00
2017-06-16 00:00:00
2017-07-31 00:00:00
2017-09-14 00:00:00
2017-06-27 00:00:00
2017-08-11 00:00:00
2017-09-25 00:00:00
2017-08-22 00:00:00
2017-07-19 00:00:00
2017-10-17 00:00:00
2017-06-15 00:00:00
2017-09-13 00:00:00
2017-06-26 00:00:00
2017-08-10 00:00:00
2017-07-07 00:00:00
2017-08-21 00:00:00
2017-07-18 00:00:00
2017-08-29 00:00:00
2017-07-26 00:00:00


99

In [52]:
np.array(X).shape

(99, 1, 121)

In [53]:
X = np.array(X).reshape(int(nr_days), nr_feats*no_companies)
X.shape

(99, 121)

Y for Regression

In [55]:
df_labels = df[["Timestamp","Next_Day_Return"]].copy()
df_labels["Next_Day_Return"].values.reshape(nr_days, no_companies)

array([[ 0.02824548,  0.01471044,  0.00438102, ...,  0.01102099,
        -0.00152892, -0.00438006],
       [ 0.        ,  0.        , -0.00043526, ...,  0.        ,
         0.01720048,  0.00134976],
       [-0.01592476, -0.00321967, -0.01402916, ...,  0.00280112,
         0.0190883 ,  0.00033693],
       ...,
       [ 0.01906216,  0.01496218,  0.01381961, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.03811681,  0.02081052,  0.01937467, ...,  0.03019974,
         0.00124835,  0.02300986],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

Y for Classification

In [56]:
df_labels = df[["Timestamp","relabeled_returns"]].copy()
df_labels["relabeled_returns"].values.reshape(nr_days, no_companies)

array([[ 1,  1,  1, ...,  1, -1, -1],
       [ 1,  1, -1, ...,  1,  1,  1],
       [-1, -1, -1, ...,  1,  1,  1],
       ...,
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1]], dtype=int64)

In [154]:
#df_labels_single = df_labels.groupby("Timestamp").agg("last")

In [155]:
#df_labels_single.head()

005930.KS       VIV    ALV.DE       TSS   BAYN.DE      TSLA  \
Timestamp                                                                 
2018-05-02   0.000000 -0.010665  0.013549 -0.013838  0.003419  0.004093   
2018-05-03   0.000000 -0.020217 -0.009181  0.008611  0.003507 -0.057051   
2018-05-04  -0.020973 -0.008056  0.008478  0.014659  0.018926  0.033328   
2018-05-08   0.013397 -0.010487 -0.003489  0.010593 -0.003532 -0.002646   
2018-05-09  -0.032853 -0.017471 -0.008826  0.005824  0.004120  0.016031   

              AIR.DE      AAPL    BAS.DE    BMW.DE  
Timestamp                                           
2018-05-02  0.007473  0.043227  0.011060  0.006682  
2018-05-03  0.000612  0.001811 -0.017219 -0.010041  
2018-05-04  0.006401  0.038483  0.012625 -0.006532  
2018-05-08 -0.002593  0.004795  0.002798  0.004142  
2018-05-09 -0.010843  0.007016  0.002906  0.000218

In [57]:
#Y = df_labels["Next_Day_Return"].values.reshape(nr_days, 10)#df_labels_single.values
Y = df_labels["relabeled_returns"].values.reshape(nr_days, no_companies)
Y.shape

(99, 11)

In [58]:
from sklearn.preprocessing import MinMaxScaler
scaler      = MinMaxScaler(feature_range=(0, 1))
rescaled    = scaler.fit_transform(X)

In [59]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, LeakyReLU

from keras import backend as K

from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping, ModelCheckpoint

from keras import optimizers
from keras.losses import binary_crossentropy
#from keras.optimizers import SGD

from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score

C:\Users\Nils\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [68]:
X_train, X_val, y_train, y_val = train_test_split(rescaled, Y, test_size=0.2, random_state=42)
#X_train, X_val, y_train, y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

In [69]:
dims = X.shape[1]
print(dims, 'dims')
print("Building model...")

nb_classes = Y.shape[1]
print(nb_classes, 'classes')

121 dims
Building model...
11 classes


In [62]:
print(X_train.shape)
print(y_train.shape)

(79, 121)
(79, 11)


### Andi

In [76]:
model = Sequential()

# Add layers
model.add(Dense(Y.shape[1], input_shape=(dims,), kernel_initializer='uniform', activation="relu"))
model.add(Dense(Y.shape[1]**2, kernel_initializer='uniform', activation="relu"))
model.add(Dense(Y.shape[1]**2, kernel_initializer='uniform', activation="relu"))
model.add(Dense(Y.shape[1], kernel_initializer='uniform', activation="sigmoid"))

model.compile(loss="binary_crossentropy",
              optimizer="SGD",
              metrics=['accuracy']) # Accuracy performance metric

hist = model.fit(X_train, y_train,
                 epochs=100,
                 batch_size=30,
                 verbose=2,
                 validation_data=(X_val, y_val))

### PREDICTION ###
y_pred = model.predict(X_val)
y_head = np.round(y_pred, 0)

### EVALUATE Classification - MODEL ###

score = model.evaluate(X_val, y_val,verbose=1)


Train on 8 samples, validate on 3 samples
Epoch 1/100
 - 1s - loss: 0.6505 - acc: 0.2500 - val_loss: 0.4616 - val_acc: 0.1333
Epoch 2/100
 - 0s - loss: 0.5118 - acc: 0.2125 - val_loss: 0.2696 - val_acc: 0.1000
Epoch 3/100
 - 0s - loss: 0.3556 - acc: 0.1500 - val_loss: -1.5043e-02 - val_acc: 0.1000
Epoch 4/100
 - 0s - loss: 0.1434 - acc: 0.1250 - val_loss: -2.9672e-01 - val_acc: 0.0333
Epoch 5/100
 - 0s - loss: -7.0619e-02 - acc: 0.1000 - val_loss: -6.3139e-01 - val_acc: 0.0333
Epoch 6/100
 - 0s - loss: -3.0750e-01 - acc: 0.0875 - val_loss: -1.0227e+00 - val_acc: 0.0333
Epoch 7/100
 - 0s - loss: -5.6318e-01 - acc: 0.0875 - val_loss: -1.5514e+00 - val_acc: 0.0333
Epoch 8/100
 - 0s - loss: -8.9050e-01 - acc: 0.0875 - val_loss: -2.4426e+00 - val_acc: 0.0333
Epoch 9/100
 - 0s - loss: -1.4198e+00 - acc: 0.0875 - val_loss: -3.6657e+00 - val_acc: 0.0333
Epoch 10/100
 - 0s - loss: -1.7960e+00 - acc: 0.0875 - val_loss: -2.8827e+00 - val_acc: 0.0333
Epoch 11/100
 - 0s - loss: -2.0651e+00 - acc: 0

In [77]:
score

[-1.3606109619140625, 0.13333334028720856]

### Nils

In [79]:
model = Sequential()

#Optimizer
sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.6, nesterov=True)

#Input Layer
model.add(Dense(nb_classes, input_shape=(dims,), activation="softmax"))#LeakyReLU(alpha=0.3)

#Hidden Layers
model.add(Dense(300, activation=LeakyReLU(alpha=0.3), use_bias=True))
model.add(Dropout(0.4))
model.add(Dense(500, activation="relu", use_bias=True))
model.add(Dropout(0.5))
model.add(Dense(300, activation="relu", use_bias=True))
#model.add(Activation('softplus'))

#Output Layer
model.add(Dense(nb_classes, activation="sigmoid"))


model.compile(optimizer="sgd", loss='binary_crossentropy', metrics=["accuracy"])

model.fit(X_train, y_train, validation_data = (X_val, y_val), epochs=30, 
          batch_size=128, verbose=True)

score = model.evaluate(X_val, y_val,verbose=1)

C:\Users\Nils\Anaconda3\lib\site-packages\keras\activations.py:103: UserWarning: Do not pass a layer instance (such as LeakyReLU) as the activation argument of another layer. Instead, advanced activation layers should be used just like any other layer in a model.
  ).format(identifier=identifier.__class__.__name__))


Train on 79 samples, validate on 20 samples
Epoch 1/30
79/79 [==============================] - 1s 13ms/step - loss: 0.6909 - acc: 0.2278 - val_loss: 0.6894 - val_acc: 0.2000
Epoch 2/30
79/79 [==============================] - 0s 202us/step - loss: 0.6894 - acc: 0.2186 - val_loss: 0.6891 - val_acc: 0.2000
Epoch 3/30
79/79 [==============================] - 0s 380us/step - loss: 0.6903 - acc: 0.2221 - val_loss: 0.6887 - val_acc: 0.1864
Epoch 4/30
79/79 [==============================] - 0s 329us/step - loss: 0.6891 - acc: 0.2083 - val_loss: 0.6884 - val_acc: 0.1727
Epoch 5/30
79/79 [==============================] - 0s 380us/step - loss: 0.6889 - acc: 0.2048 - val_loss: 0.6880 - val_acc: 0.1591
Epoch 6/30
79/79 [==============================] - 0s 380us/step - loss: 0.6885 - acc: 0.1933 - val_loss: 0.6877 - val_acc: 0.1455
Epoch 7/30
79/79 [==============================] - 0s 392us/step - loss: 0.6899 - acc: 0.1772 - val_loss: 0.6873 - val_acc: 0.1409
Epoch 8/30
79/79 [===============

In [95]:
score

[-8.998761177062988, 0.0]

In [135]:
X[0]

array([  5.51000000e+02,   8.21914827e-02,   2.06793140e-01,
        -1.01450000e-02,   4.14600000e-02,   2.13785000e-01,
         7.24430000e-01,  -6.32340000e-01,   0.00000000e+00,
        -2.09731234e-02,  -8.05570083e-03,   8.47804836e-03,
         1.46592056e-02,   1.89255091e-02,   3.33283517e-02,
         6.40083466e-03,   3.84833470e-02,   1.26254066e-02,
        -6.53170186e-03,   3.51000000e+02,  -6.38005924e-05,
         2.54183595e-01,  -1.81920000e-01,  -3.94000000e-02,
         2.19880000e-01,   6.17980000e-01,  -6.99633333e-01,
         0.00000000e+00,  -2.09731234e-02,  -8.05570083e-03,
         8.47804836e-03,   1.46592056e-02,   1.89255091e-02,
         3.33283517e-02,   6.40083466e-03,   3.84833470e-02,
         1.26254066e-02,  -6.53170186e-03,   2.04900000e+03,
         7.03780595e-02,   2.13552659e-01,  -2.62300000e-02,
         3.96700000e-02,   2.10740000e-01,   7.28870000e-01,
        -9.91700000e-01,   0.00000000e+00,  -2.09731234e-02,
        -8.05570083e-03,

In [58]:
E = model.predict(X[0].reshape(1,90))
E

array([[0.0000000e+00, 1.0000000e+00, 1.2261952e-27, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 6.2738419e-01, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00]], dtype=float32)

In [59]:
Y[0]

array([-0.01721889, -0.05705099, -0.01746398, -0.00918132,  0.00061175,
        0.00181067,  0.00350719, -0.0202173 ,  0.        , -0.01004057])

In [139]:
EY[0]

array([[ 0.04923758,  0.05990248,  0.12029236,  0.14767935,  0.1304228 ,
         0.04514487,  0.12636857,  0.00601043,  0.12278158,  0.1271591 ]])